// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Perpustakaan.Data;

namespace Web_Perpustakaan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220203203353_Tb_User")]
    partial class Tb_User
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Web_Perpustakaan.Models.Buku", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Gambar")
                        .HasColumnType("text");

                    b.Property<string>("Judul_Buku")
                        .HasColumnType("text");

                    b.Property<string>("Penerbit")
                        .HasColumnType("text");

                    b.Property<string>("Pengarang")
                        .HasColumnType("text");

                    b.Property<string>("Tahun_Terbit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Buku");
                });

            modelBuilder.Entity("Web_Perpustakaan.Models.Peminjaman", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Alamat")
                        .HasColumnType("text");

                    b.Property<string>("BukuId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Nama_Lengkap")
                        .HasColumnType("text");

                    b.Property<string>("No_Handphone")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tgl_Peminjaman")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Tgl_Pengembalian")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("BukuId");

                    b.ToTable("Tb_Peminjaman");
                });

            modelBuilder.Entity("Web_Perpustakaan.Models.Pengembalian", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Nama_Lengkap")
                        .HasColumnType("text");

                    b.Property<string>("Peminjaman")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Tgl_Kembali")
                        .HasColumnType("text");

                    b.Property<string>("Tgl_Kembali_Seharusnya")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Peminjaman");

                    b.ToTable("Tb_Pengembalian");
                });

            modelBuilder.Entity("Web_Perpustakaan.Models.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Roles");
                });

            modelBuilder.Entity("Web_Perpustakaan.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Username");

                    b.HasIndex("RolesId");

                    b.ToTable("Tb_User");
                });

            modelBuilder.Entity("Web_Perpustakaan.Models.Peminjaman", b =>
                {
                    b.HasOne("Web_Perpustakaan.Models.Buku", "FkBuku")
                        .WithMany()
                        .HasForeignKey("BukuId");

                    b.Navigation("FkBuku");
                });

            modelBuilder.Entity("Web_Perpustakaan.Models.Pengembalian", b =>
                {
                    b.HasOne("Web_Perpustakaan.Models.Peminjaman", "FkPeminjaman")
                        .WithMany()
                        .HasForeignKey("Peminjaman");

                    b.Navigation("FkPeminjaman");
                });

            modelBuilder.Entity("Web_Perpustakaan.Models.User", b =>
                {
                    b.HasOne("Web_Perpustakaan.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
